### PR TITLE
Remove value attribute to prevent overwriting values & adjust pin names to default

### PR DESCRIPTION
**Pull request by samyk**

### CODE REVIEW

**Comment by LonghornEngineer** [comment]
Adjusting the pin names from ("P$1" to "1") will break anyone currently using these libraries. In Eagle the default for making new pins is the P$1 format so this will stay the same.

**Comment by samyk** [comment]
Eagle comes with plenty of default LBRs, and you'll notice that not a **single one** of them uses the "P$1" format, thus if anyone wishes to actually swap out their parts for yours (in order to more cleanly go into the MacroFab workflow), they'll be left manually deleting parts, adding the MacroFab part, reconnecting nets, then having to manually reroute the components on board layout. This makes it unreasonable to swap out parts for MacroFab's.

If you look at any other well known library, you'll also see they all prefer the numeric pin naming convention -- eg Adafruit, Sparkfun, etc:
https://github.com/sparkfun/SparkFun-Eagle-Libraries/blob/master/SparkFun-Resistors.lbr
https://raw.githubusercontent.com/adafruit/Adafruit-Eagle-Library/master/adafruit.lbr

I would still suggest committing the VALUE attribute change. This library is the only one I've ever used which *overwrites* values when replacing components, which is another reason it's difficult for me to move my designs over to MacroFab (which was the goal of both commits -- make it easier for users of traditional Eagle designs to begin using the MacroFab library and service).

**Comment by LonghornEngineer** [comment]
Yes I am working on a fix for the Value attribute. 

Changing the pin default names will not happen however as it will break everyone that is currently using the libraries.

**Comment by samyk** [comment]
I agree you don't want to break things for existing users, however it only prevents them from using the REPLACE command on an old MacroFab part to a new MacroFab part -- that I get, so I would suggest providing a legacy lbr for users that includes the old parts if the require that functionality, rather than forcing all future users who want to use your service to have parts that are incompatible with 99% of all other parts libraries and existing designs.

I'm also guessing that most existing library users aren't going to be replacing many components on a board; most users will want to replace parts in order to *start* using your libraries and service.

FYI, I did submit a feature suggestion to Eagle a few months ago to support both formats so that the software could handle this specific case, but I wouldn't expect this to get baked in as again, this library is one of the corner cases. https://forums.autodesk.com/t5/eagle-forum/allow-replacing-parts-with-different-pin-naming-conventions/td-p/6858384

**Comment by samyk** [comment]
Doesn't f1ab1fa9bfdcab5f61a983de1e0328aa718988f1 already solve the value attribute issue?

**Comment by LonghornEngineer** [comment]
The problem isnt current users replacing parts but when you update a library it will look at the pins and find a mismatch. Basically you won't be able to use the "updated" library on any board designed with the older version.

**Comment by samyk** [comment]
Sorry, maybe I'm missing something -- the way I understand it, if you're only updating the pin names (as in my commit) and you perform the UPDATE command on the library, not only will it cleanly update without error, but it will also "fix" the user's schematic and board to use the new pin names. If you *move* the part location/size in the LBR and change the pin names (which is not happening), then I'd expect an issue. (Even if there were an issue, Eagle copies the parts into the schematic/board, so even an incompatible, updated LBR can still be used with the old design, you just wouldn't be able to do the "REPLACE"s -- but I don't think this is the case with the update I provided).

Additionally, you can provide this library as the legacy library for users in case they ever need it. SparkFun does this with their Retired library for example: https://github.com/sparkfun/SparkFun-Eagle-Libraries/blob/master/SparkFun-Retired.lbr

**Pull request closed without merging**
